spring:
  application:
    name: crm
  datasource:
    url: jdbc:postgresql://${DB_HOST}/db_crm
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: ${JWT_SECRET}
    expiracao-segundos: ${JWT_EXPIRACAO_SEGUNDOS}
  admin:
    nome: ${ADMIN_NOME}
    email: ${ADMIN_EMAIL}
    senha: ${ADMIN_SENHA}